version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "**/*"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
