grafana:
  image: grafana/grafana:6.6.0-beta1
  env_file:
    - .env
  ports:
    - '3090:3000'
  volumes:
    - ./:/var/lib/grafana/plugins/google-sheets-datasource
  #   - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
    - GF_LOG_LEVEL=debug
    - GF_DATAPROXY_LOGGING=true
    - GF_FEATURE_TOGGLES_ENABLE=expressions
