version: "3"
services:
  ##
  # Use this service to test the circle-ci image against the plugin
  #
  build-env:
    image: d518c1ad9c7a
    network_mode: bridge 
    container_name: circle-ci-dev
    user: root
    volumes:
      - ${PWD}:/home/circleci/plugin
    stdin_open: true
    tty: true
    user: circleci
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT:-3000}
      - GF_PATHS_PROVISIONING=/home/stephanie/src/provisioning
      - GF_PATHS_PLUGINS=/home/stephanie/src/plugins
      - GF_PATHS_DATA=/home/stephanie/src/grafana/data
