name: Identify Changes

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string
    outputs:
      source:
        value: ${{ jobs.changes.outputs.source }}
      dependencies:
        value: ${{ jobs.changes.outputs.dependencies }}
      internal_events:
        value: ${{ jobs.changes.outputs.internal_events }}
      cue:
        value: ${{ jobs.changes.outputs.cue }}
      component_docs:
        value: ${{ jobs.changes.outputs.component_docs }}
      markdown:
        value: ${{ jobs.changes.outputs.markdown }}
      install:
        value: ${{ jobs.changes.outputs.install }}
      k8s:
        value: ${{ jobs.changes.outputs.k8s }}

jobs:
  changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      source: ${{ steps.filter.outputs.source }}
      dependencies: ${{ steps.filter.outputs.dependencies }}
      internal_events: ${{ steps.filter.outputs.internal_events }}
      cue: ${{ steps.filter.outputs.cue }}
      component_docs: ${{ steps.filter.outputs.component_docs }}
      markdown: ${{ steps.filter.outputs.markdown }}
      install: ${{ steps.filter.outputs.install }}
      k8s: ${{ steps.filter.outputs.k8s }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ inputs.base_ref }}
        ref: ${{ inputs.head_ref }}
        # TODO check if worth keying off the other internal components that the k8s tests utilize, suspect not.
        filters: |
          source:
            - ".github/workflows/test.yml"
            - ".cargo/**"
            - "benches/**"
            - "lib/**"
            - "proto/**"
            - "scripts/**"
            - "src/**"
            - "tests/**"
            - "build.rs"
            - "Cargo.lock"
            - "Cargo.toml"
            - "Makefile"
            - "rust-toolchain.toml"
            - "vdev/**"
          deny:
            - 'deny.toml'
            - "vdev/**"
          dependencies:
            - ".cargo/**"
            - 'Cargo.toml'
            - 'Cargo.lock'
            - 'rust-toolchain.toml'
            - '.github/workflows/pr.yml'
            - 'Makefile'
            - 'scripts/cross/**'
            - "vdev/**"
          cue:
            - 'website/cue/**'
            - "vdev"
          component_docs:
            - 'scripts/generate-component-docs.rb'
            - "vdev/**"
          markdown:
            - '**/**.md'
            - "vdev/**"
          internal_events:
            - 'src/internal_events/**'
            - "vdev/**"
          docker:
            - 'distribution/docker/**'
            - "vdev/**"
          install:
            - ".github/workflows/install-sh.yml"
            - "distribution/install.sh"
          k8s:
            - "src/sources/kubernetes_logs/**"

          amqp:
            - "src/amqp.rs"
            - "src/internal_events/amqp.rs"
            - "src/sinks/amqp/**"
            - "src/sources/amqp.rs"
          appsignal:
            - "src/sinks/appsignal/**"
          aws:
            - "src/aws_**"
            - "src/internal_events/aws_**"
            - "src/sources/aws_**"
            - "src/sinks/aws_**"
            - "src/transforms/aws_**"
          axiom:
            - "src/sinks/axiom.rs"
          azure:
            - "src/sinks/azure_**"
          clickhouse:
            - "src/sinks/clickhouse/**"
