# This workflow identifies changes between the base and the head ref, for use in
# other workflows to decide if they should be executed.

name: Identify Changes

on:
  workflow_call:
    # These inputs allow the filter action to be able to access the correct refs for
    # comparison in changes detection, it is required as this is called from the
    # merge_group context.
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string
    outputs:
      source:
        value: ${{ jobs.changes.outputs.source }}
      dependencies:
        value: ${{ jobs.changes.outputs.dependencies }}
      internal_events:
        value: ${{ jobs.changes.outputs.internal_events }}
      cue:
        value: ${{ jobs.changes.outputs.cue }}
      component_docs:
        value: ${{ jobs.changes.outputs.component_docs }}
      markdown:
        value: ${{ jobs.changes.outputs.markdown }}
      install:
        value: ${{ jobs.changes.outputs.install }}
      all-int:
        value: ${{ jobs.changes-integrations.outputs.all-int }}
      k8s:
        value: ${{ jobs.changes-integrations.outputs.k8s }}
      amqp:
        value: ${{ jobs.changes-integrations.outputs.amqp }}
      appsignal:
        value: ${{ jobs.changes-integrations.outputs.appsignal }}
      aws:
        value: ${{ jobs.changes-integrations.outputs.aws }}
      axiom:
        value: ${{ jobs.changes-integrations.outputs.axiom }}
      azure:
        value: ${{ jobs.changes-integrations.outputs.azure }}
      clickhouse:
        value: ${{ jobs.changes-integrations.outputs.clickhouse }}
      databend:
        value: ${{ jobs.changes-integrations.outputs.databend }}
      datadog:
        value: ${{ jobs.changes-integrations.outputs.datadog }}
      dnstap:
        value: ${{ jobs.changes-integrations.outputs.dnstap }}
      docker-logs:
        value: ${{ jobs.changes-integrations.outputs.docker-logs }}
      elasticsearch:
        value: ${{ jobs.changes-integrations.outputs.elasticsearch }}
      eventsoredb:
        value: ${{ jobs.changes-integrations.outputs.eventsoredb }}
      fluent:
        value: ${{ jobs.changes-integrations.outputs.fluent }}
      gcp:
        value: ${{ jobs.changes-integrations.outputs.gcp }}
      humio:
        value: ${{ jobs.changes-integrations.outputs.humio }}
      http-client:
        value: ${{ jobs.changes-integrations.outputs.http-client }}
      influxdb:
        value: ${{ jobs.changes-integrations.outputs.influxdb }}
      kafka:
        value: ${{ jobs.changes-integrations.outputs.kafka }}
      logstash:
        value: ${{ jobs.changes-integrations.outputs.logstash }}
      loki:
        value: ${{ jobs.changes-integrations.outputs.loki }}
      mongodb:
        value: ${{ jobs.changes-integrations.outputs.mongodb }}
      nats:
        value: ${{ jobs.changes-integrations.outputs.nats }}
      nginx:
        value: ${{ jobs.changes-integrations.outputs.nginx }}
      opentelemetry:
        value: ${{ jobs.changes-integrations.outputs.opentelemetry }}
      postgres:
        value: ${{ jobs.changes-integrations.outputs.postgres }}
      prometheus:
        value: ${{ jobs.changes-integrations.outputs.prometheus }}
      pulsar:
        value: ${{ jobs.changes-integrations.outputs.pulsar }}
      redis:
        value: ${{ jobs.changes-integrations.outputs.redis }}
      shutdown:
        value: ${{ jobs.changes-integrations.outputs.shutdown }}
      splunk:
        value: ${{ jobs.changes-integrations.outputs.splunk }}
      webhdfs:
        value: ${{ jobs.changes-integrations.outputs.webhdfs }}

jobs:
  # General source code changes
  changes:
    runs-on: ubuntu-20.04
    outputs:
      source: ${{ steps.filter.outputs.source }}
      dependencies: ${{ steps.filter.outputs.dependencies }}
      internal_events: ${{ steps.filter.outputs.internal_events }}
      cue: ${{ steps.filter.outputs.cue }}
      component_docs: ${{ steps.filter.outputs.component_docs }}
      markdown: ${{ steps.filter.outputs.markdown }}
      install: ${{ steps.filter.outputs.install }}
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ inputs.base_ref }}
        ref: ${{ inputs.head_ref }}
        filters: |
          source:
            - ".github/workflows/test.yml"
            - ".cargo/**"
            - "benches/**"
            - "lib/**"
            - "proto/**"
            - "scripts/**"
            - "src/**"
            - "tests/**"
            - "build.rs"
            - "Cargo.lock"
            - "Cargo.toml"
            - "Makefile"
            - "rust-toolchain.toml"
            - "vdev/**"
          deny:
            - 'deny.toml'
            - "vdev/**"
          dependencies:
            - ".cargo/**"
            - 'Cargo.toml'
            - 'Cargo.lock'
            - 'rust-toolchain.toml'
            - '.github/workflows/pr.yml'
            - 'Makefile'
            - 'scripts/cross/**'
            - "vdev/**"
          cue:
            - 'website/cue/**'
            - "vdev"
          component_docs:
            - 'scripts/generate-component-docs.rb'
            - "vdev/**"
          markdown:
            - '**/**.md'
            - "vdev/**"
          internal_events:
            - 'src/internal_events/**'
            - "vdev/**"
          docker:
            - 'distribution/docker/**'
            - "vdev/**"
          install:
            - ".github/workflows/install-sh.yml"
            - "distribution/install.sh"

  changes-integrations:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      all-int: ${{ steps.filter.outputs.all-int }}
      k8s: ${{ steps.filter.outputs.k8s }}
      amqp: ${{ steps.filter.outputs.amqp }}
      appsignal: ${{ steps.filter.outputs.appsignal}}
      aws: ${{ steps.filter.outputs.aws }}
      axiom: ${{ steps.filter.outputs.axiom }}
      azure: ${{ steps.filter.outputs.azure }}
      clickhouse: ${{ steps.filter.outputs.clickhouse }}
      databend: ${{ steps.filter.outputs.databend }}
      datadog: ${{ steps.filter.outputs.datadog }}
      dnstap: ${{ steps.filter.outputs.dnstap }}
      docker-logs: ${{ steps.filter.outputs.docker-logs }}
      elasticsearch: ${{ steps.filter.outputs.elasticsearch }}
      evenstoredb: ${{ steps.filter.outputs.evenstoredb }}
      fluent: ${{ steps.filter.outputs.fluent }}
      gcp: ${{ steps.filter.outputs.gcp }}
      humio: ${{ steps.filter.outputs.humio }}
      http-client: ${{ steps.filter.outputs.http-client }}
      influxdb: ${{ steps.filter.outputs.influxdb }}
      kafka: ${{ steps.filter.outputs.kafka }}
      logstash: ${{ steps.filter.outputs.logstash }}
      loki: ${{ steps.filter.outputs.loki }}
      mongodb: ${{ steps.filter.outputs.mongodb }}
      nats: ${{ steps.filter.outputs.nats }}
      nginx: ${{ steps.filter.outputs.nginx }}
      opentelemetry: ${{ steps.filter.outputs.opentelemetry }}
      postgres: ${{ steps.filter.outputs.postgres }}
      prometheus: ${{ steps.filter.outputs.prometheus }}
      pulsar: ${{ steps.filter.outputs.pulsar }}
      redis: ${{ steps.filter.outputs.redis }}
      shutdown: ${{ steps.filter.outputs.shutdown }}
      splunk: ${{ steps.filter.outputs.splunk }}
      webhdfs: ${{ steps.filter.outputs.webhdfs }}
    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ inputs.base_ref }}
        ref: ${{ inputs.head_ref }}
        filters: scripts/integration/ci_file_detection_filters.yaml
