name: CLI - Linux

on:
  workflow_call:
  issue_comment:
    types: [created]

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug
  # observing issues fetching boringssl via HTTPS in the OSX build, seeing if this helps
  # can be removed when we switch back to the upstream openssl-sys crate
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test-cli:
    runs-on: [linux, ubuntu-20.04-8core]
    env:
      CARGO_INCREMENTAL: 0
    if: |
      github.event_name == 'workflow_call'
        || (github.event_name == 'issue_comment')
#        || (github.event_name == 'issue_comment' && contains(github.event.payload.comment.body, '/ci-deploy-cli'))
    steps:
      - name: test
        run: echo "OK"

      - name: Get PR branch
        if: ${{ github.event_name != 'workflow_call' }}
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        if: ${{ github.event_name != 'workflow_call' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'workflow_call' }}

      - name: Cache Cargo registry + index
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: echo "OK"
      #- run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      #- run: bash scripts/environment/prepare.sh
      #- run: echo "::add-matcher::.github/matchers/rust.json"
      # - run: make test-cli
      # - name: Upload test results
      #   run: scripts/upload-test-results.sh
      #   if: always()
