name: Integration Test Suite

on:
  workflow_call:
    inputs:
      if:
        required: false
        type: boolean
      test_name:
        required: true
        type: string
  workflow_dispatch:
  #issue_comment:
  #  types: [created]
  #merge_group:
  #  types: [checks_requested]

#concurrency:
  # `github.event.number` exists for pull requests, otherwise fall back to SHA for merge queue
#  group: ${{ github.workflow }}-${{ github.event.number || github.event.merge_group.base_sha }}
#  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  AXIOM_TOKEN: ${{ secrets.AXIOM_TOKEN }}
  TEST_APPSIGNAL_PUSH_API_KEY: ${{ secrets.TEST_APPSIGNAL_PUSH_API_KEY }}
  CONTAINER_TOOL: "docker"
  DD_ENV: "ci"
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  RUST_BACKTRACE: full
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  test-integration:
    #name: Integration - Linux, ${{ inputs.test_name }}
    runs-on: [linux, ubuntu-20.04-8core]
    if: ${{ inputs.if }}
    timeout-minutes: 20
    steps:
      # For PR comment trigger, extra steps are required to associate the workflow with the PR.

      # # Find the branch that the comment was made in.
      # - name: (PR comment) Get PR branch
      #   if: ${{ github.event_name == 'issue_comment' }}
      #   uses: xt0rted/pull-request-comment-branch@v1
      #   id: comment-branch

      # # Indicate in the PR's CI pane that this job is running.
      # - name: (PR comment) Set latest commit status as pending
      #   if: ${{ github.event_name == 'issue_comment' }}
      #   uses: myrotvorets/set-commit-status-action@master
      #   with:
      #     sha: ${{ steps.comment-branch.outputs.head_sha }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     status: pending

      # # Checkout the branch, using the PR ref.
      # - name: (PR comment) Checkout PR branch
      #   if: ${{ github.event_name == 'issue_comment' }}
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ steps.comment-branch.outputs.head_ref }}

      # Checkout the default branch otherwise.
      # - name: Checkout branch
      #   if: ${{ github.event_name != 'issue_comment' }}
      #   uses: actions/checkout@v3

      - name: mock
        run: echo "OK"

      # - run: make ci-sweep

      # - run: sudo npm -g install @datadog/datadog-ci

      # - run: make test-integration-${{ matrix.test }}
      #   env:
      #     TEST_DATADOG_API_KEY: ${{ secrets.CI_TEST_DATADOG_API_KEY }}
      #     SPLUNK_VERSION: ${{ matrix.env.SPLUNK_VERSION }}

      # - name: Upload test results
      #   run: scripts/upload-test-results.sh
      #   if: always()

      # - run: make test-integration-${{ matrix.test }}-cleanup
      #   if: ${{ always() }}
      #   env:
      #     TEST_DATADOG_API_KEY: ${{ secrets.CI_TEST_DATADOG_API_KEY }}
      #     SPLUNK_VERSION: ${{ matrix.env.SPLUNK_VERSION }}

      # Indicate in the PR's CI pane that this job is complete if necessary
      # - name: (PR comment) Set latest commit status as failure
      #   uses: myrotvorets/set-commit-status-action@master
      #   if: failure() && github.event_name == 'issue_comment'
      #   with:
      #     sha: ${{ steps.comment-branch.outputs.head_sha }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     status: 'failure'

    #if: |
    #    (github.event_name != 'issue_comment' || contains(github.event.comment.body, '/ci-deploy-integration-tests'))
    #      && github.event_name != 'pull_request'
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     include:
    #       - test: 'amqp'
    #         if: ${{ inputs.amqp }} == true
          #- test: 'appsignal'
          #- test: 'aws'
          #- test: 'axiom'
          # - test: 'azure'
          # - test: 'clickhouse'
          # - test: 'databend'
          #- test: 'datadog-agent'
          #- test: 'datadog-logs'
          #- test: 'datadog-metrics'
          #- test: 'datadog-traces'
          # - test: 'dnstap'
          # - test: 'docker-logs'
          # - test: 'elasticsearch'
          # - test: 'eventstoredb'
          # - test: 'fluent'
          # - test: 'gcp'
          # - test: 'humio'
          # - test: 'http-client'
          # - test: 'influxdb'
          # - test: 'kafka'
          # - test: 'logstash'
          # - test: 'loki'
          # - test: 'mongodb'
          # - test: 'nats'
          # - test: 'nginx'
          # - test: 'opentelemetry'
          # - test: 'postgres'
          # - test: 'prometheus'
          # - test: 'pulsar'
          # - test: 'redis'
          # - test: 'shutdown'
          # - test: 'splunk'
          # - test: 'webhdfs'

  # test-integration-check:
  #   name: Integration Tests
  #   runs-on: ubuntu-20.04
  #   if: (github.event_name != 'issue_comment' || contains(github.event.comment.body, '/ci-deploy-integration-tests')) && always()
  #   needs:
  #     - test-integration
  #   steps:
  #     # Find the branch that the comment was made in.
  #     - name: (PR comment) Get PR branch
  #       if: github.event_name == 'issue_comment' && needs.test-integration.result == 'success'
  #       uses: xt0rted/pull-request-comment-branch@v1
  #       id: comment-branch

  #     # Indicate in the PR's CI pane that this job is complete
  #     - name: (PR comment) Set latest commit status as success
  #       uses: myrotvorets/set-commit-status-action@master
  #       if: github.event_name == 'issue_comment' && needs.test-integration.result == 'success'
  #       with:
  #         sha: ${{ steps.comment-branch.outputs.head_sha }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         status: 'success'

  #     - name: validate
  #       run: |
  #         if [ ${{ github.event_name }} == 'pull_request' ] ; then
  #             echo "success"
  #             exit 0
  #         fi
  #         if [ ${{ needs.test-integration.result }} == 'failure' ] ; then
  #             echo "failed"
  #             exit 1
  #         fi
  #         echo "success"
  #         exit 0
